spring.application.name=SPRING-3
server.port=9090
#TASK 3 DAY-3
#2026-03-09T16:36:03.778+05:30  INFO 39852 --- [SPRING-3] [           main]
# o.s.boot.tomcat.TomcatWebServer
#: Tomcat started on port 9090 (http) with context path '/'
##TASK 4 DAY-3
#Use YAML configuration to create ports
app.name= My Spring boot application